POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Headache in the time of Coronajana",
    "author": "Riikka Dimnik",
    "url": "https://www.google.com/",
    "likes": 11
}